repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-case-conflict
      - id: check-xml
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: fix-encoding-pragma
